spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: "Amazon Cognito"
            authorization-grant-type: authorization_code
        provider:
          cognito:
          cognito:
            issuer-uri: ${COGNITO_ISSUER_URI}
            user-name-attribute: sub

server:
  port: 8080
